version: '3.8'

services:
  web:
    build: .
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/appdatabase
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: appdatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
