"""points_ratio_fill_gaps column for group

Revision ID: 18e609943047
Revises: 2cd39476f268
Create Date: 2024-07-21 14:16:12.045154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e609943047'
down_revision = '2cd39476f268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_ratio_fill_gaps', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_group', schema=None) as batch_op:
        batch_op.drop_column('points_ratio_fill_gaps')

    # ### end Alembic commands ###
