"""empty message

Revision ID: 19092fe1a4a6
Revises: 31349b6627bd
Create Date: 2024-07-13 15:43:02.533490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19092fe1a4a6'
down_revision = '31349b6627bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('part_of_speech', sa.String(length=20), nullable=True),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_defined',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['definition.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', 'definition_id', name='_word_definition_uc')
    )
    op.create_table('wordgroup_worddefined',
    sa.Column('wordgroup_id', sa.Integer(), nullable=False),
    sa.Column('worddefined_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['worddefined_id'], ['word_defined.id'], ),
    sa.ForeignKeyConstraint(['wordgroup_id'], ['word_group.id'], ),
    sa.PrimaryKeyConstraint('wordgroup_id', 'worddefined_id')
    )
    op.drop_table('words_groups')
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('definition', sa.String(length=512), nullable=True))
        batch_op.drop_column('meaning')

    with op.batch_alter_table('word_group', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_group', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meaning', sa.VARCHAR(length=512), nullable=True))
        batch_op.drop_column('definition')

    op.create_table('words_groups',
    sa.Column('word_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['word_group.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'group_id')
    )
    op.drop_table('wordgroup_worddefined')
    op.drop_table('word_defined')
    op.drop_table('definition')
    # ### end Alembic commands ###
