"""Definition: word_text column for cases when api returns definitions for nearby words

Revision ID: aaf166c2a264
Revises: 19092fe1a4a6
Create Date: 2024-07-13 19:00:54.410932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf166c2a264'
down_revision = '19092fe1a4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('definition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_text', sa.String(length=64), nullable=True))

    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.alter_column('word_text',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_column('definition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('definition', sa.VARCHAR(length=512), nullable=True))
        batch_op.alter_column('word_text',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('definition', schema=None) as batch_op:
        batch_op.drop_column('word_text')

    # ### end Alembic commands ###
