"""WordDefined deleted now WordGroups include Definitions itselves

Revision ID: e99437ead80c
Revises: aaf166c2a264
Create Date: 2024-07-14 23:08:35.022974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99437ead80c'
down_revision = 'aaf166c2a264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups_association',
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['definition.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['word_group.id'], ),
    sa.PrimaryKeyConstraint('definition_id', 'group_id')
    )
    op.drop_table('wordgroup_worddefined')
    op.drop_table('word_defined')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_defined',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word_id', sa.INTEGER(), nullable=False),
    sa.Column('definition_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['definition.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', 'definition_id', name='_word_definition_uc')
    )
    op.create_table('wordgroup_worddefined',
    sa.Column('wordgroup_id', sa.INTEGER(), nullable=False),
    sa.Column('worddefined_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['worddefined_id'], ['word_defined.id'], ),
    sa.ForeignKeyConstraint(['wordgroup_id'], ['word_group.id'], ),
    sa.PrimaryKeyConstraint('wordgroup_id', 'worddefined_id')
    )
    op.drop_table('groups_association')
    # ### end Alembic commands ###
